@extends('admin.public.plugins')
@section('header')
    @include('admin.public.header')
@endsection
@section('sidebar')
    @include('admin.public.sidebar')
@endsection
@section('content')
    @include('admin.public.content')
@endsection
